
// Auto-generated by AutoPilot on 29-07-2023 at 01:25:16

const express = require('express');
const router = express.Router();

// Count the number of vowels in the query parameter called prompt
router.get('/AiBlog', (req, res) => {
    try {
        // Count the number of vowels
        const answer = (req.query.prompt.match(/[aeiou]/gi) || []).length;
        res.status(200).json({ result: answer });
    } catch (error) {
        res.status(503).json({ error: 'Encountered an error' });
    }
});

module.exports = router;